services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss_wallabag
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - ./fresh_rss_data:/var/www/FreshRSS/data
      - ./:/var/www/FreshRSS/extensions/freshrss-wallabag-button:ro
    ports:
      - 8080:80
    depends_on:
      - wallabag

  wallabag:
    image: wallabag/wallabag
    container_name: wallabag
    environment:
      SYMFONY__ENV__DOMAIN_NAME: "http://localhost:8081"
    ports:
      - 8081:80
    volumes:
      - ./wallabag_data/images:/var/www/wallabag/web/assets/images
      - ./wallabag_data/data:/var/www/wallabag/data
